version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 2
  tests: false
  build-tags:
    - mytag
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
  go: "1.23"
  concurrency: 4

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
  path-prefix: ""
  path-mode: "abs"
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: true
  new-from-merge-base: main
  new-from-rev: HEAD
  new-from-patch: ""
  whole-files: true
  fix: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/Proteus-Crypto/kraken-crypt)
    gofumpt:
      extra-rules: true
    golines:
      max-len: 120
      tab-len: 4
  exclusions:
    warn-unused: true
    generated: strict
    paths:
      - ".*\\.my\\.go$"
      - lib/bad.go

linters:
  default: all
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gosec
    - goconst
    - gocyclo
    - dupl
    - lll
    - funlen
    - mnd
    - nakedret
    - prealloc
    - unconvert
    - whitespace
    - gocritic
    - gocognit
    - gochecknoinits
    - gochecknoglobals
    - gomodguard
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - iotamixing
    - ireturn
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - unqueryvet
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl_v5
    - zerologlint
  disable:
    - gochecknoinits
    - gochecknoglobals
    - mnd
    - funlen
    - gosec
    - unused
